### ISSUE TITLE
text_at options

### ISSUE THREAD

**Issue by Hermanverschooten** [andrewtimberlake/elixir-pdf#11]
I am a bit confused about the options you can give to `text_at` with a `binary` vs a `list`.
If I am correct to only options available to a `binary` is `:kerning`,
while the `list` variant takes `:font_size`, `leading`, `color`, `bold`,`italic`, but no `:kerning`.

Can't we make it so that both variants take the same options?

**Comment by Hermanverschooten** [comment]
After digging deeper, I see that `:kerning` is given at a different level and applies to the whole.

Maybe `text_at` should be able to take an `attributed_text` with it being in a list?

**Comment by andrewtimberlake** [comment]
Thanks for this. I will work on aligning the two methods so they are more consistent and interchangeable.

**Comment by andrewtimberlake** [comment]
I’ve had a look, both `text_at/4` and `text_wrap/4` take attributed text and both take global options. You can set kerning in the global options or for an individual string in a list.
See: https://github.com/andrewtimberlake/elixir-pdf/blob/a17353be9e03fe9d49ef8166be44db8677802b9a/test/pdf/page_test.exs#L145-L190
Let me know with a failing test if there’s something else I’ve missed.

**Comment by Hermanverschooten** [comment]
I see, they indeed both take a list of attributed text, but `text_wrap` also allows options like `:bold`, ... to be supplied for the whole text, `text_at` ignores those except for `:kerning`.
```elixir
text_at({x, y}, "175", bold: true, font_size: 20)
```
renders 
```
BT
/F1 12 Tf
212.5984 722.8346 Td
(175) Tj
ET
```
```elixir
text_wrap!({x,y},{72, 20},  "175", bold: true, font_size: 20)
```
renders
```
BT
/F1 12 Tf
212.5984 707.3146 Td
/F2 20 Tf
(175) Tj
ET
```
