### ISSUE TITLE
Measurement conversions

### ISSUE THREAD

**Issue by Hermanverschooten** [andrewtimberlake/elixir-pdf#13]
https://github.com/andrewtimberlake/elixir-pdf/blob/47d32f4f8a26937b9317795444d8bb0725718150/lib/pdf.ex#L21

Why are you using `72.21` as a base for the calculations?
Every doc (even the official pdf documentation) specifies 1 point = 1/72 inch.
I am converting PDF's from Ruby Prawn and was wondering why all my positions were wrong.

**Comment by andrewtimberlake** [comment]
That came directly from erlguten. I have changed it to 72.
