### ISSUE TITLE
Question on add_page

### ISSUE THREAD

**Issue by flowerpower234** [andrewtimberlake/elixir-pdf#28]
Hello, 
I would like to thank you for this master piece of work.
Still, I have trouble using `add_page` as I actually don't get it work as I fugred out, so I must be missing some obvious stuff.

when I use your sample and do

Pdf.build([size: :a4, compress: true], fn pdf ->
  pdf
  |> Pdf.set_info(title: "Demo PDF")
  |> Pdf.set_font("Helvetica", 10)
  |> Pdf.add_page(:a4)
  |> Pdf.write_to("test.pdf")
end)

I do get a pdf with to empty pages

but when I do

Pdf.build([size: :a4, compress: true], fn pdf ->
  pdf
  |> Pdf.set_info(title: "Demo PDF")
  |> Pdf.set_font("Helvetica", 10)
  |> Pdf.add_page(:a4)
  |> Pdf.text_at({200,200}, "Welcome to Pdf")
  |> Pdf.write_to("test.pdf")
end)

System is hanging till timeout, instead of getting a pdf with two pages and "Welcome to Pdf" on the second page.

So could you help me understand what I'm doing wrong ?

Thank you so much

**Comment by flowerpower234** [comment]
Hello again, I've found on my own by studying the test scripts, so I got my answers on the mandatory steps to have pages when needded. Happy end :)
Thank again for this awesome work, I will try to providee you with PRs to enhance a bit this or there. I was thinking of underlying text, text justifying ...

**Comment by Jayshua** [comment]
For anyone coming along in the future, you need to set the font after creating a new page before you can use `text_at`.

```elixir
   pdf
   |> Pdf.new_page(:a4)
   |> Pdf.set_font("Helvetica", 18)
   |> Pdf.text_at({200, 200}, "Welcome")
```
