### ISSUE TITLE
Alternating style for rows in a table

### ISSUE THREAD

**Issue by Hermanverschooten** [andrewtimberlake/elixir-pdf#29]
Hi Andrew,

Is there currently a way to set alternating styles, eg background, for rows in a table?

Thx,

Herman

**Comment by andrewtimberlake** [comment]
You can now #30 Let me know if this works for you.

**Comment by Hermanverschooten** [comment]
Works perfectly!

**Comment by Hermanverschooten** [comment]
I added a PR on top of #30 to expand/correct the docs for `table`.
