### ISSUE TITLE
Is there a way to calculate the width of some text?

### ISSUE THREAD

**Issue by brainbolt** [andrewtimberlake/elixir-pdf#46]
My goal is to center text on the page. I don't see an option for that in the API, but I could do it manually if there was some way to know what the width of a block of text would be.

**Comment by andrewtimberlake** [comment]
With attributed text, you can set `align: :left | :center | :right`
See (L85): https://github.com/andrewtimberlake/elixir-pdf/blob/ecf11a0bbe7e865e9a58562337909fc20a52da08/test/pdf_test.exs#L81-L87

Alternatively you can use `Pdf.Font.text_width/3`

**Comment by brainbolt** [comment]
🙏
