### ISSUE TITLE
Large number of processes after upgrading to 0.7.0

### ISSUE THREAD

**Issue by Nilsonn** [andrewtimberlake/elixir-pdf#47]
Hey 👋 After upgrading to 0.7.0, we see an increase in memory and in process counts.
Previous version: 0.6.3

We use a Phoenix server and generate simple pdf receipts.

Normally, we have a constant usage of memory of ~370 MB and now the yellow line increases to ~450 MB. The red one is strangely not increasing that much but is still increasing. This could be related to the load balancer.

<img width="1192" alt="Bildschirmfoto 2024-07-23 um 08 17 52" src="https://github.com/user-attachments/assets/ce70bb11-b24f-4566-afb0-b694cd0e4543">

## Yellow line server
Total processes: ~3600
Processes from the PDF library: ~2974

<img width="1307" alt="Bildschirmfoto 2024-07-23 um 08 18 37" src="https://github.com/user-attachments/assets/73d19d25-d078-49fa-b9ec-402c561b6eda">

## Red line server
Total processes: ~1000
Processes from the PDF library: ~370
<img width="1307" alt="Bildschirmfoto 2024-07-23 um 08 18 46" src="https://github.com/user-attachments/assets/61cef788-a4c6-4b6e-bc6a-2ec811d38659">

I tried to reproduce it locally and started the server and looped over the only function that uses this library:
```
Enum.each(1..3000, fn _ -> FileGenerator.generate_binary(line_width: 12, textlines: [%{text: "Textline"}], title: "A receipt") end)
```
This creates 6000 processes that are not closed.

This PDF code is executed under the hood:
```
Pdf.build([size: [receipt.width, receipt.height], compress: true], fn pdf ->
      pdf
      |> Pdf.set_info(title: title, creator: "foobar")
      |> Pdf.set_font(receipt.font, receipt.font_size)
      |> Pdf.text_lines(receipt.text_start_pos, receipt.textlines)
      |> Pdf.export()
    end)
```

I will rollback to 0.6.3 for now. Let me know if you need more information.

**Comment by andrewtimberlake** [comment]
I’m sorry about this. There was a memory leak in cleaning up linked processes during PDF cleanup. I have fixed the bug (released 0.7.1) and put in tests to ensure process clean up on normal cleanup and in the event of a process crash.
