### ISSUE TITLE
missing tag breaks exdoc links

### ISSUE THREAD

**Issue by jvantuyl** [andrewtimberlake/elixir-pdf#49]
When browsing on `hexdocs.pm`, the `</>` icons link to Github with the expectation that the version will be tagged.  There don't appear to be tags for any versions past 0.6.x and this breaks the links.  Should be an easy fix.  I'd send a PR, but... can't really send a PR for a tag that I know of.

**Comment by andrewtimberlake** [comment]
Thans @jvantuyl 
Sorry, I forgot to push tags for the last two releases. It is now fixed the doc links are working
